[package]
name = "rscheme"
version = "1.0.0"
authors = ["Elisabeth Henry <liz.henry@ouvaton.org>"]
description = "A toy scheme interpreter written in Rust"
readme = "README.md"
homepage = "https://github.com/lady-segfault/rscheme"
[dependencies]
log = "0.3.1"

